<a href="https://colab.research.google.com/github/rizqyilmi/python-class/blob/main/Simple_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np



In [3]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [7]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
print(training_inputs)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [9]:
training_outputs = np.array([[0,1,1,0]]).T
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [13]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3, 1)) -1
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [14]:
for iteration in range(1):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))



In [15]:
print('Output after training')
print(outputs)

Output after training
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]
